tasks:
  - init: |
      python -m venv venv
      source venv/bin/activate
      python -m pip install --upgrade pip wheel setuptools
      python -m pip install Django
      python manage.py migrate
    command: |
      source venv/bin/activate
      python manage.py runserver
  
ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
